### PR TITLE
fix ppo accelerate

### PR DESCRIPTION
**Pull request by ell-hol**
In response to @tangerye 's issue in #2 @
Fixed a few bugs that were plaguing the PPO training when using accelerate launch on a multi-gpu setup
I included an examples.py for reference

### CODE REVIEW

**Comment by lucidrains** [comment]
@ell-hol thank you Yacine

**Comment by tengerye** [comment]
Hi @ell-hol @lucidrains thank you so much for your kind help. However, I got the following error from the latest codebase.
```
  File "/home/ubuntu/workspace/PaLM-rlhf-pytorch/examples.py", line 52, in <module>
    trainer.train(
  File "/home/ubuntu/workspace/PaLM-rlhf-pytorch/palm_rlhf_pytorch/ppo.py", line 614, in train
    ) = self.actor_critic.module.generate(
  File "/opt/conda/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ActorCritic' object has no attribute 'module'. Did you mean: 'modules'?
```

**Comment by ell-hol** [comment]
@tengerye First configure accelerate in interactive mode for your setup:
```
accelerate config
```
Then execute the script using the accelerate launcher :

```
accelerate launch examples.py
``` 

You can also do both in one line, for ex for a single node with 4 GPUs :
```
accelerate launch \
  --num_processes=4 \
  --num_machines=1 \
  --machine_rank=0 \
  --gpu_ids=0,1,2,3 \
  examples.py
```

**Comment by lucidrains** [comment]
@ell-hol i think what's going on is the single gpu case is broken

**Comment by tengerye** [comment]
> @tengerye First configure accelerate in interactive mode for your setup:
> 
> ```
> accelerate config
> ```
> 
> Then execute the script using the accelerate launcher :
> 
> ```
> accelerate launch examples.py
> ```
> 
> You can also do both in one line, for ex for a single node with 4 GPUs :
> 
> ```
> accelerate launch \
>   --num_processes=4 \
>   --num_machines=1 \
>   --machine_rank=0 \
>   --gpu_ids=0,1,2,3 \
>   examples.py
> ```

I can run well on this way indeed. May I ask do we plan to make it compatible with one GPU?

**Comment by lucidrains** [comment]
@tengerye i'll leave it to Yacine, i'm sure he can figure this out, it is just a conditional

**Comment by ell-hol** [comment]
@tengerye @lucidrains you guys are right, it's fixed now in the new PR

**Pull request merged**
